# 김영한님은 yml을 좋아하셔서 application.properties를 지우고 yml 생성.
# 설정파일 복잡해지면 yml이 낫다.

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=true
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    # show_sql: true   System.out에 하이버네이트 실행 SQL을 남긴다
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug # // logger을 통해 하이버네이트 실행 SQL을 남긴다
    org.hibernate.type: trace # 쿼리 파라미터 로그 남기기 values(?, ?)에 실제로 무슨 값 들어갔는지 밑에 로그로 찍어줌.
